# Add configuration values here, as shown below.

development:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: qwerty
  DATABASE_HOST: db_host
  CLOUD_NAME: cloudinary_cloud_name
  CLOUDINARY_API_KEY: cloudinary_api_key
  CLOUDINARY_API_SECRET: cloudinary_api_secret

production:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: qwerty
  DATABASE_HOST: db_host
  CLOUD_NAME: cloudinary_cloud_name
  CLOUDINARY_API_KEY: cloudinary_api_key
  CLOUDINARY_API_SECRET: cloudinary_api_secret
